INSERT INTO when2raid.tipos (nombre_tipo) 
    VALUES
    ("The Epic of Alexander (Ultimate)"),
    ("The Unending Coil of Bahamut (Ultimate)"),
    ("The Weapon's Refrain (Ultimate)"),
    ("Dragonsong's Reprise (Ultimate)"),
    ("The Omega Protocol (Ultimate)"),
    ("Futures Rewritten (Ultimate)"),
    ("The Binding Coil of Bahamut"),
    ("The Second Coil of Bahamut"),
    ("The Second Coil of Bahamut (Savage)"),
    ("The Final Coil of Bahamut"),
    ("Alexander: Gordias"),
    ("Alexander: Gordias (Savage)"),
    ("Alexander: Midas"),
    ("Alexander: Midas (Savage)"),
    ("Alexander: The Creator"),
    ("Alexander: The Creator (Savage)"),
    ("Omega: Deltascape"),
    ("Omega: Deltascape (Savage)"),
    ("Omega: Sigmascape"),
    ("Omega: Sigmascape (Savage)"),
    ("Omega: Alphascape"),
    ("Omega: Alphascape (Savage)"),
    ("Eden's Gate"),
    ("Eden's Gate (Savage)"),
    ("Eden's Verse"),
    ("Eden's Verse (Savage)"),
    ("Eden's Promise"),
    ("Eden's Promise (Savage)"),
    ("Pandaemonium: Asphodelos"),
    ("Pandaemonium: Asphodelos (Savage)"),
    ("Pandaemonium: Abyssos"),
    ("Pandaemonium: Abyssos (Savage)"),
    ("Pandaemonium: Anabaseios"),
    ("Pandaemonium: Anabaseios (Savage)	");